language: java
jdk:
  - oraclejdk8
  
script:
  - ./mvnw test -B

install:
# update mvnw
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  # webhooks:
  email: false
